### PR TITLE
Big refactoring and updates, migration to .NET Standard 2.0

### PR DESCRIPTION
**Pull request by Digiman**
- Made some of updates and refactor the code.
- Migrated to .NET Standard 2.0.
- Updated and fixed NuGet package definition.
- Updated dependencies.
- Used a reworked version of the Authentication library (https://github.com/Digiman/CyberSource.Authentication).

### CODE REVIEW

**Comment by Digiman** [comment]
@gnongsie or @akshunyaInfy please take a look at this request! I hope it can help to bring a new platform and functionality.
Changes here also made to align code style and naming conversions in .NET C# works but not as in Java!

**Comment by xantari** [comment]
This is good, this library needs a lot of help. I have opened many bugs in last couple of days.

**Comment by Digiman** [comment]
> This is good, this library needs a lot of help. I have opened many bugs in last couple of days.

Thanks, this library need for my solution at least to download reports. And right now only my solution is working. Original solution, library and code don't working.

Ideally someone who works with this library need to take a look on our fixes, comments and apply all of them and resolve issues because for now - library not ready to use in production. But...in my case, i don't have another solution - i need to continue use my updates because this is only one way to get reports from CyberSource(((

**Review by devdreamsolution — APPROVED** [review]

**Comment by gnongsie** [comment]
Closing this as no longer valid.

.NET Standard SDK is present in [cybersource-rest-client-dotnetstandard](https://github.com/cybersource/cybersource-rest-client-dotnetstandard)

**Pull request closed without merging**
